### PR TITLE
Feature: KeyHive Sofle RGB

### PR DESCRIPTION
**Pull request by filoxo**
There were 3 fixes: 

- limit LED brightness to avoid the controller from freezing up
- detect handedness
- fix the VIA json to match the new matrix

After those were working, I also:

- cleaned up unused files
- moved common settings upwards as possible
- reused/shared code as possible
- moved from keyboards/sofle folder to keyboards/keyhive/sofle so that conflicts and changes didn't need workarounds. This necessitated a new productId and therefore a new VIA json file. See the via keymap README for instructions on how to use/test for VIA compatibility.

### CODE REVIEW

**Comment by tpstevens** [comment]
I'm testing this branch out now because it makes sense that it should be treated as a separate board, and it seems like it has the latest LED settings. I've only built the left side so far, so that's the only part I've tested. I'm using QMK toolbox to flash it.

Seems to me that the LAYOUT changes are only necessary when flashing with VIA enabled-- for the default and the VIA keymaps (with VIA disabled in rules.mk), I had to undo the changes to the LAYOUT macro parameters in the "Fix matrix weirdness" commit ad1f916 (not the pin wirings, just the L45 and L40 rotation) to get the bottom row to work properly.

That makes me wonder if there's something with the keyhive-sofle VIA json that needs to be fixed. I haven't used VIA before, so I'm not sure what to look for.

**Comment by filoxo** [comment]
Thanks for testing it, I appreciate the help! Maybe you could try to also undo my changes to the VIA json at commit https://github.com/keyhive/qmk_firmware/pull/1/commits/a7f31fb97e3fe74cd25f31d78dec0c6f4af72955 and test that to see if it works correctly for you.

**Comment by tpstevens** [comment]
I tried to test that, but I'm running into a different problem now (so I went back to your json changes).  I'm having a weird issue with VIA -- whenever I build a keymap with VIA enabled, the VIA configurator doesn't recognize the keyboard and any changes that I make to the keymap code don't take effect. I've tried resetting the EEPROM through bootmagic and QMK toolbox, installing the latest QMK toolbox and reinstalling all the drivers, deleting the .build folder, and using "-c" to clean intermediate files before building -- no dice. Any idea on what the issue could be? I've confirmed that the firmware size is in fact changing with each build (whenever I delete a layer, etc), and QMK toolbox isn't reporting any errors.

**Comment by filoxo** [comment]
Hmm I don't know why that might be because VIA is a blackbox due to being closed source. I recall seeing [a message in the QMK discord that says you have to have exactly 4 layers for VIA keymaps](https://discord.com/channels/440868230475677696/537514291440517121/837401636283482153) but doesn't explain why. Maybe its that?

Just to be sure, are you also using the included keyhive-sofle.json? Because since I'm considering this a different keyboard, I used a different productId so it won't detect it without also uploading that json file.

**Comment by tpstevens** [comment]
Ahh, I didn't upload the json to VIA as a draft -- didn't realize that was required. Your json changes are correct then, but I ended up reverting your LAYOUT changes for all keymaps and it worked properly. What issue were you seeing with LAYOUT that led you to make that change?

**Comment by filoxo** [comment]
I believe its because the physical matrix is actually different. I haven't been able to obtain gerbers for both to be able to compare but if I flash this version of the Sofle with the original VIA keymap, the left side bottom row is all out of order. This is also why I felt it was better to move out of the sofle folder: in order to avoid confusion because the hardware is slightly different (to accommodate for the LEDs I'm supposing).

**Comment by tpstevens** [comment]
Makes sense, I definitely agree with moving it out. It looks like the matrix pin change was required — but if you undo only the LAYOUT change (like I did), does it still work on your board?

**Comment by filoxo** [comment]
"Works" for the VIA keymap but messes up the order of the bottom row for the default keymap. Not sure why. I reached out for help on the QMK discord but didn't get any responses. Is there a reason for not wanting to keep the LAYOUT changes? That was the only way I could get both of the keymaps to work as expected.

**Comment by tpstevens** [comment]
Weird, that's not what I'm seeing. I'm only testing the left keyboard because that's what I've soldered :)

With all your changes as written:

- Default: The bottom row sends LAlt, LCTL, MO(1), Enter, and Mute, and the encoder sends LWin. (**doesn't match keymap.c**)
- VIA: VIA configurator shows the bottom row as LAlt, LCTL, MO(1), Enter, and Mute (and each key sends the corresponding code). Pressing the encoder sends LWin. (**doesn't match keymap.c**)

With all your changes except for the LAYOUT changes:

- Default: The bottom row sends LWin, LAlt, LCTL, MO(1), and Enter, and the encoder sends Mute (**matches keymap.c**)
- VIA: Initially, the VIA configurator shows the bottom row as  LAlt, LCTL, MO(1), Enter, and Mute, and the encoder sends LWin. However, I remapped all the keys to the correct ones (based on keymap.c) and it works properly now.

I then tested the following (starting with the old LAYOUT before your changes):

- I closed and reopened VIA and loaded the draft json -- still works.
- I flashed the default keymap again -- still works.
- I reapplied your LAYOUT changes, flashed the VIA keymap, and the VIA configurator matched the keymap and all the keys worked as intended -- ???
- I flashed the default keymap with the LAYOUT changes -- now the bottom row sends the incorrect keys (LAlt, LCTL, MO(1), Enter, and Mute).
- I cleared the EEPROM using QMK toolbox, flashed the default keymap with the LAYOUT changes -- the bottom row still sends the incorrect keys.

I'm just making a guess here, but I wonder if there's something going on with how VIA stores layouts that isn't being cleared by QMK Toolbox's Clear EEPROM command. If you tested with the original Sofle VIA keymap first, you would have had to make the LAYOUT changes for the Keyhive's Sofle -- but that does mess up the default keymap.

Try undoing the LAYOUT changes, flashing the VIA keymap, and correcting the keys using the VIA configurator.

**Comment by filoxo** [comment]
OK but I still don't see any justification to removing that code. I don't think its a big deal to leave it so that I don't have to ask people to live with it until they change it for the first time. Its an extra hoop just to... remove code I already wrote that works for both layouts. I've gotten reports from 3 other people that the via keymap plus the json work perfectly for them.

**Comment by tpstevens** [comment]
I agree that the VIA key map works, but it messes up the default (non-VIA) layout. Can you try it to confirm?

**Comment by filoxo** [comment]
Alright, I'm finishing up a second one tonight and so I can test each keymap with different physical hardware. Thanks again for testing!

**Comment by tpstevens** [comment]
Sweet, I’m interested to see what you find. If you don’t mind, try the VIA one without the LAYOUT changes first — that might confirm my theory about the VIA configuration persisting.

**Comment by openam** [comment]
I had to update the `oled.c` to show when I switched the default layer from `0` to `1`. I had to change from:

```
    switch (get_highest_layer(layer_state)) {
```
to this: 
```
    uint8_t layer = layer_state ? biton(layer_state) : biton32(default_layer_state);
    switch (layer) {
```

It appears that the layer state isn't set when you are on the default layer.

**Comment by ryancrosby** [comment]
I just built a keyhive sofle rgb, and am working on getting it programmed with my layout. I have ran into problems with QMK on this keyboard and it has taken a bit to get working. This pull request was a great help in getting something working. It would be great to see this ultimately merged to the mainline qmk firmware branch, I have a fork of that so it would be much easier for me and I assume others. I am happy to help ensure things are working.

For now I have moved this new keyboard configuration over to my branch and tested it, https://github.com/ryancrosby/qmk_firmware/tree/ryancrosby/keyboards/keyhive/sofle_rgb. I don't use via and the bottom row was indeed off by one key. I had to revert the LAYOUT function to the old one to get the bottom row to work correctly.

As an aside, my led backlights are not working on the left side. This is only my second keyboard build, so I think I messed something up in the build. But consequently, I may not be the best end to end tester. But I am happy to help.

Let me know if there is anything I can do.

**Comment by filoxo** [comment]
Thanks everyone for your input! I've been swamped with life in general, and so this PR has languished. Once I finish with the busiest part of other projects I will return to this. ETA two weeks.

**Comment by eXsoR65** [comment]
> 
> 
> I just built a keyhive sofle rgb, and am working on getting it programmed with my layout. I have ran into problems with QMK on this keyboard and it has taken a bit to get working. This pull request was a great help in getting something working. It would be great to see this ultimately merged to the mainline qmk firmware branch, I have a fork of that so it would be much easier for me and I assume others. I am happy to help ensure things are working.
> 
> For now I have moved this new keyboard configuration over to my branch and tested it, https://github.com/ryancrosby/qmk_firmware/tree/ryancrosby/keyboards/keyhive/sofle_rgb. I don't use via and the bottom row was indeed off by one key. I had to revert the LAYOUT function to the old one to get the bottom row to work correctly.
> 
> As an aside, my led backlights are not working on the left side. This is only my second keyboard build, so I think I messed something up in the build. But consequently, I may not be the best end to end tester. But I am happy to help.
> 
> Let me know if there is anything I can do.

Have you since been able to test the RGB? or got it working? I just purchased a kit and see this so wanted to see if there anything I can do to help my self.

**Comment by tpstevens** [comment]
@ryancrosby, you might want to post pictures of your soldering job in the r/MechanicalKeyboards questions thread or in pretty much any keyboard Discord server. I'm happy to help too, but we should probably keep soldering questions out of Github issues. Maybe drop a link to where you post it?

**Comment by filoxo** [comment]
Closing in favor of https://github.com/qmk/qmk_firmware/pull/15339

**Comment by winder** [comment]
@filoxo wish I had noticed your PR earlier, I re-invented the wheel a bit while learning QMK! Please feel free to leave feedback on qmk#15339 in case I missed anything. You have at least 6 months of extra experience compared to me :)

**Pull request closed without merging**
